[package]
name = "quic_client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = {workspace = true}
quinn = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
rustls = {workspace = true}
